### ISSUE TITLE
/cs

### ISSUE THREAD

**Issue by NarwhaloteChavalote** [thexiao77/UkranianMemeTelegramBot#31]
Request para llamar a todos mis amigos lo counterstikeros para videojugar al videojuego de disparar con armas como en la vida real pero estando quieto y la ppbizon es una mierda y no existe

**Comment by adrianvillanueva997** [comment]
Okay. Mañana estará listo

**Comment by adrianvillanueva997** [comment]
Ya está hecho.

[Más información](https://github.com/adrianvillanueva997/UkranianMemeTelegramBot/commit/ee8850036e89b7288d80b7aa3bddeba326ad9ef4)
